from django.urls import path
from . import views
from django.views.generic import TemplateView 

urlpatterns = [
    path('', views.home, name='home'),
    path('tour/', views.tour_list, name='tour'),
    path('tour-about/', views.tour_about, name='tour_about'),
    path('about/', views.about_us, name='about_us'),
    path('reviews/', views.reviews_view, name='reviews'),
    path('gallery/', views.gallery_view, name='gallery'),
    path('blog/', views.blog_view, name='blog'),
    path('blog-about/', views.blog_about, name='blog_about'),
    path('partners/', TemplateView.as_view(template_name='partners.html'), name='partners'),
    path('corp-tour/', TemplateView.as_view(template_name='corp_tour.html'), name='corp_tour'),
    path('indi-tour/', TemplateView.as_view(template_name='indi_tour.html'), name='indi_tour'),
    path('sign-tour/', TemplateView.as_view(template_name='sign_tour.html'), name='sign_tour'),
    path('kz/', views.kz_view, name='kz'),
    path('uz/', views.uz_view, name='uz'),
    path('gallery-kz/', views.gallery_kz_view, name='gallery_kz'),
    path('gallery-uz/', views.gallery_uz_view, name='gallery_uz'),
    path('submit-application/', views.submit_application, name='submit_application'),
    path("tour/about/1/",  views.tour_about_1,  name="tour_about_1"),
    path("tour/about/2/",  views.tour_about_2,  name="tour_about_2"),
    path("tour/about/3/",  views.tour_about_3,  name="tour_about_3"),
    path("tour/about/4/",  views.tour_about_4,  name="tour_about_4"),
    path("tour/about/5/",  views.tour_about_5,  name="tour_about_5"),
    path("tour/about/6/",  views.tour_about_6,  name="tour_about_6"),
    path("tour/about/7/",  views.tour_about_7,  name="tour_about_7"),
    path("tour/about/8/",  views.tour_about_8,  name="tour_about_8"),
    path("tour/about/9/",  views.tour_about_9,  name="tour_about_9"),
    path("tour/about/10/", views.tour_about_10, name="tour_about_10"),
    path("tour/about/11/", views.tour_about_11, name="tour_about_11"),
    path("tour/about/12/", views.tour_about_12, name="tour_about_12"),
    path('blog_about1/', views.blog_about1, name='blog_about1'),
    path('blog_about2/', views.blog_about2, name='blog_about2'),
    path('blog_about3/', views.blog_about3, name='blog_about3'),
    path('blog_about4/', views.blog_about4, name='blog_about4'),
    path('blog_about5/', views.blog_about5, name='blog_about5'),
    path('blog_about6/', views.blog_about6, name='blog_about6'),
    path('blog_about7/', views.blog_about7, name='blog_about7'),
    path('blog_about8/', views.blog_about8, name='blog_about8'),
    path('tour_about_UZ1/', views.tour_about_UZ1, name='tour_about_UZ1'),
    path('tour_about_UZ2/', views.tour_about_UZ2, name='tour_about_UZ2'),
]

